
#Crop Farmer settings
[crop_farmer]
	#How much FE the crop farmer can store
	#Range: > 0
	crop_farmer_store = 10000
	#How much FE the crop farmer can use per tick
	#Range: > 0
	crop_farmer_use_per_tick = 20
	#How many ticks must pass before the crop farmer works
	#Range: 20 ~ 200
	crop_farmer_tick = 40

#Melon and Pumpkin Farmer settings
[melon_farmer]
	#How much FE the melon and pumpkin farmer can store
	#Range: > 0
	melon_farmer_store = 10000
	#How much FE the melon and pumpkin farmer can use per tick
	#Range: > 0
	melon_farmer_use_per_tick = 20
	#How many ticks must pass before the melon and pumpkin farmer works
	#Range: 20 ~ 200
	melon_farmer_tick = 40

#Nether Wart Farmer settings
[nether_wart_farmer]
	#How much FE the nether wart farmer can store
	#Range: > 0
	nether_wart_farmer_store = 10000
	#How much FE the nether wart farmer can use per tick
	#Range: > 0
	nether_wart_farmer_use_per_tick = 20
	#How many ticks must pass before the nether wart farmer works
	#Range: 20 ~ 200
	nether_wart_farmer_tick = 40

#Cocoa Beans Farmer settings
[cocoa_beans_farmer]
	#How much FE the cocoa beans farmer can store
	#Range: > 0
	cocoa_beans_farmer_store = 10000
	#How much FE the cocoa beans farmer can use per tick
	#Range: > 0
	cocoa_beans_farmer_use_per_tick = 20
	#How many ticks must pass before the cocoa beans farmer works
	#Range: 20 ~ 200
	cocoa_beans_farmer_tick = 40

#Cactus Farmer settings
[cactus_farmer]
	#How much FE the cactus farmer can store
	#Range: > 0
	cactus_farmer_store = 10000
	#How much FE the cactus farmer can use per tick
	#Range: > 0
	cactus_farmer_use_per_tick = 20
	#How many ticks must pass before the cactus farmer works
	#Range: 20 ~ 200
	cactus_farmer_tick = 40

#Sugar Canes Farmer settings
[sugar_canes_farmer]
	#How much FE the sugar canes farmer can store
	#Range: > 0
	sugar_canes_farmer_store = 10000
	#How much FE the sugar canes farmer can use per tick
	#Range: > 0
	sugar_canes_farmer_use_per_tick = 20
	#How many ticks must pass before the sugar canes farmer works
	#Range: 20 ~ 200
	sugar_canes_farmer_tick = 40

#Bamboo Farmer settings
[bamboo_farmer]
	#How much FE the bamboo farmer can store
	#Range: > 0
	bamboo_farmer_store = 10000
	#How much FE the bamboo farmer can use per tick
	#Range: > 0
	bamboo_farmer_use_per_tick = 20
	#How many ticks must pass before the bamboo farmer works
	#Range: 20 ~ 200
	bamboo_farmer_tick = 40

